# Generated by Django 3.0.6 on 2021-01-25 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='First Name', max_length=120)),
                ('l_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('grade', models.TextField(null=True)),
                ('student', models.BooleanField(default=False)),
                ('administrator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('username', models.CharField(default='username1', max_length=120)),
                ('grade', models.CharField(max_length=120)),
                ('interest_shown', models.CharField(max_length=120, null=True)),
                ('num_activities_in', models.CharField(max_length=120)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('tag1', models.CharField(max_length=120)),
                ('tag2', models.CharField(max_length=120, null=True)),
                ('tag3', models.CharField(max_length=120, null=True)),
                ('advisor_name', models.CharField(max_length=120)),
                ('low', models.BooleanField(default=False)),
                ('medium', models.BooleanField(default=False)),
                ('high', models.BooleanField(default=False)),
                ('num_times', models.CharField(max_length=120)),
                ('leader1', models.CharField(max_length=120)),
                ('leader2', models.CharField(max_length=120, null=True)),
                ('leader3', models.CharField(max_length=120, null=True)),
                ('leader4', models.CharField(max_length=120, null=True)),
                ('mission_statement', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('protocols', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
