# Generated by Django 3.0.6 on 2021-01-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210126_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.TextField(default='JPIS Debate Club'),
            preserve_default=False,
        ),
    ]
