# Generated by Django 3.0.6 on 2021-02-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventMember',
        ),
    ]
