# Generated by Django 3.0.6 on 2021-03-27 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_delete_eventmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(default=datetime.date(2021, 3, 27), max_length=120),
        ),
    ]
